=== bluecmd/safaripark/jsfp/src/nl/nikhef/sfp/ddmi/desc/sfpdd.xsd
<!--
  SaFariPark SFP+ editor
  Copyright (C) 2017 National Institute for Subatomic Physics Nikhef
  
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Types -->
	<xs:simpleType name="unsignedInt">
		<xs:union memberTypes="xs:unsignedInt">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:pattern value="x[0-9A-Fa-f]{1,9}" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>

	<xs:simpleType name="unsignedByte">
		<xs:union memberTypes="xs:unsignedByte">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:pattern value="x[0-9A-Fa-f]{1,2}" />
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>


	<xs:complexType name="identifier" mixed="false">
		<xs:attribute type="xs:ID" name="id" use="optional" />
	</xs:complexType>

	<xs:complexType name="element" mixed="false">
		<xs:complexContent>
			<xs:extension base="identifier">
				<xs:attribute type="xs:string" name="label" use="optional" />
				<xs:attribute type="xs:string" name="short" use="optional" />
				<xs:attribute type="xs:string" name="name" use="optional" />
				<xs:attribute type="xs:IDREF" name="password-id" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="value" mixed="false">
		<xs:complexContent>
			<xs:extension base="element">
				<xs:attribute type="xs:boolean" name="writable" use="optional" />
				<xs:attribute type="xs:boolean" name="monitor" use="optional" />
				<xs:attribute type="unsignedByte" name="offset" use="required" />
				<xs:attribute type="unsignedByte" name="length" use="required" />
				<xs:attribute type="xs:string" name="level" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="decimal" mixed="false">
		<xs:complexContent>
			<xs:extension base="value">
				<xs:sequence>
					<xs:element ref="scale" maxOccurs="unbounded" minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<!-- Root element -->
	<xs:element name="ddmi">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="identifier">
					<xs:sequence>
						<xs:element ref="source" maxOccurs="unbounded"
							minOccurs="0" />
						<xs:element ref="group" maxOccurs="unbounded"
							minOccurs="0" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<!-- Sources, checksums and cache -->

	<xs:element name="checksum">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="unsignedByte" name="offset" use="optional" />
					<xs:attribute type="unsignedByte" name="start" use="optional" />
					<xs:attribute type="unsignedByte" name="end" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="cache">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="unsignedByte" name="start" use="optional" />
					<xs:attribute type="unsignedByte" name="end" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="source">
		<xs:complexType mixed="false">
			<xs:sequence>
				<xs:element ref="checksum" maxOccurs="unbounded"
					minOccurs="0" />
				<xs:element ref="cache" minOccurs="0" />
			</xs:sequence>
			<xs:attribute type="unsignedByte" name="i2c-addr" use="optional" />
			<xs:attribute type="xs:ID" name="id" use="optional" />
			<xs:attribute type="unsignedByte" name="start" use="optional" />
			<xs:attribute type="unsignedByte" name="end" use="optional" />
			<xs:attribute type="unsignedByte" name="page-select"
				use="optional" />
			<xs:attribute type="xs:string" name="valid-if" use="optional" />
			<xs:attribute type="unsignedByte" name="page" use="optional" />
			<xs:attribute type="xs:IDREF" name="parent-id" use="optional" />
		</xs:complexType>
	</xs:element>





	<xs:element name="group">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="element">
					<xs:choice maxOccurs="unbounded" minOccurs="0">
						<xs:element ref="int" />
						<xs:element ref="uint" />
						<xs:element ref="bitmap" />
						<xs:element ref="text" />
						<xs:element ref="group" />
						<xs:element ref="float" />
						<xs:element ref="ufix" />
						<xs:element ref="sfix" />
						<xs:element ref="password" />
					</xs:choice>
					<xs:attribute type="xs:IDREF" name="source-id" use="optional" />
					<xs:attribute type="xs:string" name="showIf" use="optional" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>



	<xs:element name="int">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="value">
					<xs:sequence>
						<xs:element ref="map" maxOccurs="unbounded" minOccurs="0" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="uint">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="value">
					<xs:sequence>
						<xs:element ref="map" maxOccurs="unbounded" minOccurs="0" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>


	<xs:element name="bitmap">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="value">
					<xs:sequence>
						<xs:element ref="bool" maxOccurs="unbounded" minOccurs="0" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="password">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="value">
					<xs:sequence>
						<!-- when a const password is set the value is applied each time on write -->
						<!-- otherwise the password is asked by the password manager (TODO) -->
						<xs:element name="const" type="xs:string" minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>


	<xs:element name="text">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="value" />
			</xs:complexContent>
		</xs:complexType>
	</xs:element>



	<xs:element name="float">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="decimal" />
			</xs:complexContent>
		</xs:complexType>
	</xs:element>


	<xs:element name="ufix">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="decimal">
					<xs:attribute type="unsignedInt" name="divider" use="optional" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="sfix">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="decimal">
					<xs:attribute type="unsignedInt" name="divider" use="optional" />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>


	<!-- Meta elements -->
	<xs:element name="bool">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:unsignedByte" name="bit" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="scale">
		<xs:complexType>
			<xs:attribute type="xs:float" name="offset" use="optional" />
			<xs:attribute type="xs:float" name="scale" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="map">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="unsignedByte" name="key" use="optional" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!-- Overlay support -->
	<xs:element name="overlay">
		<xs:complexType mixed="false">
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element ref="bool"/>
				<xs:element ref="map"/>
				<xs:element ref="scale"/>
				<xs:element ref="sfix"/>
				<xs:element ref="ufix"/>
				<xs:element ref="float"/>
				<xs:element ref="int"/>
				<xs:element ref="uint"/>
				<xs:element ref="text"/>
				<xs:element ref="bitmap"/>
				<xs:element ref="group"/>
				<xs:element ref="ddmi"/>
				<xs:element ref="source"/>
				<xs:element ref="cache"/>
				<xs:element ref="checksum"/>
				<xs:element ref="password"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== bluecmd/safaripark/overlays/sff8690.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  SaFariPark SFP+ editor
  Copyright (C) 2017 National Institute for Subatomic Physics Nikhef
  
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<!-- Adds support for the Maxim DS1856M -->
<overlay
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="sfpdd.xsd">
	
	<group id="root">
		<group label="Tunable SFP" source-id="diag_p2" showIf="isset(id.montype, 6)">
			<bitmap label="Dithering" writable="false" offset="128" length="1" name="dithering"
				level="debug">
				<bool bit="0">Selection in 50PPM steps</bool>
				<bool bit="1">Selection by channel number></bool>
				<bool bit="2">TX Dither supported</bool>
			</bitmap>
			<group label="Laser capabilities">
				<int label="First Frequency (THz)"    writable="false" name="LFL1" offset="132" length="2" level="basic" />
				<ufix label="First Frequency (GHz)" writable="false" name="LFL2" offset="134" length="2" level="basic">
					<scale scale="0.1"/>
				</ufix>
				<int label="Last Frequency (THz)"     writable="false" name="LFH1" offset="136" length="2" level="basic" />
				<ufix label="Last Frequency (GHz)"  writable="false" name="LFH2" offset="138" length="2" level="basic">
					<scale scale="0.1"/>
				</ufix>
				<ufix label="Minimum grid spacing (GHz)" writable="false" name="LGrid" offset="140" length="2" level="basic" >
					<scale scale="0.1"/>
				</ufix>
			</group>
			<group label="Frequency and wavelength control">
				<int label="Channel number set"         writable="true" name="chno_set"  offset="144" length="2" level="basic" />
				<ufix label="Wavelength set (nm)" writable="true" name="wl_set"    offset="146" length="2" level="basic" >
					<scale scale="0.05"/>
				</ufix>
				<bitmap label="Other options"         writable="true" name="tx_dither" offset="151" length="1" level="basic">
					<bool bit="0">Disable dithering</bool>
				</bitmap>
			</group>
			<group label="Status and Alarms">
				<int label="Error frequency"   writable="false" name="err_f"   offset="152" length="2" level="basic" />
				<int label="Error wavelength"  writable="false" name="err_wl"  offset="154" length="2" level="basic" />
				<bitmap label="Current status" writable="false" name="current_status" offset="168" length="1" level="basic">
					<bool bit="4">TX tune</bool>
					<bool bit="5">Wavelength Unlocked</bool>
					<bool bit="6">TEC Fault</bool>
				</bitmap>
				<bitmap label="Latched status" writable="false" name="latched_status" offset="172" length="1" level="basic">
					<bool bit="2">Unsupported TX Dither</bool>
					<bool bit="3">New Channel acquired</bool>
					<bool bit="4">Bad Channel requested</bool>
					<bool bit="5">Wavelength Unlocked</bool>
					<bool bit="6">TEC Fault</bool>
				</bitmap>
			</group>
		</group>
	</group>
	
</overlay>

=== bluecmd/safaripark/overlays/wr_loopback_eeprom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  SaFariPark SFP+ editor
  Copyright (C) 2017 National Institute for Subatomic Physics Nikhef
  
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<!-- Adds support for the Maxim DS1856M -->
<overlay
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="sfpdd.xsd">
	
	<source id="diag_p0">
		<checksum offset="247" start="128" end="246"/>
		<cache start="128" end="247"/>
	</source>
	<group id="root">
		<group label="Loopback SFP" source-id="diag_p0" showIf="isset(id.montype, 6)">
		
			<bitmap label="Magic Value"
					writable="true"
					offset="128"
					length="2"
					name="magic"
					level="basic" />
			
            <int	label="Version"
            		writable="true"
            		offset="130"
            		length="1"
            		name="version"
            		level="basic" />
            
            <bitmap	label="Calibration Date"
            		writable="true"
            		offset="131"
            		length="3"
            		name="cal_date"
            		level="basic" />
            
            <bitmap label="OUI responsible"
            		writable="true"
            		offset="134"
            		length="3"
            		name="cal_oui"
            		level="basic" />
            		
            <ufix	label="Tx-to-Rx Delay (ps)"
            		writable="true"
            		offset="140"
            		length="4"
            		name="tx2rx_dly"
            		level="basic" 
            		divider="x10000"/>
            		
            <ufix	label="Tx-to-Out Delay (ps)"
            		writable="true"
            		offset="144"
            		length="4"
            		name="tx2out_dly"
            		level="basic"
            		divider="x10000" />
            		
            <ufix	label="Rx-to-Out Delay (ps)"
            		writable="true"
            		offset="148"
            		length="4"
            		name="rx2out_dly"
            		level="basic"
            		divider="x10000" />
		</group>
	</group>
	
</overlay>

=== bluecmd/safaripark/overlays/km3net_oesol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  SaFariPark SFP+ editor
  Copyright (C) 2017 National Institute for Subatomic Physics Nikhef
  
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->


<!-- Adds support for the OE Solutions transceivers, as used in KM3NeT -->
<overlay 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="sfpdd.xsd">
	
	<group id="root">
		<group label="OE Solutions custom">

			<group source-id="diag" showIf="isset(id.montype, 6)">
				<!-- implicit hard-coded password -->
				<password id="oe-password" offset="x7b" length="4" writable="true">
					<!-- for now constants must be binary hex strings. Sorry.  -->
					<const>4F455350</const>
				</password>
			</group>
			<group source-id="diag_p4" showIf="isset(id.montype, 6)">
				<uint label="Tune value" writable="true" 
					offset="x8B" length="2" level="basic"
					password-id="oe-password">
				</uint>
			</group>
			
		</group>
	</group>
</overlay>
